sudo: required
services:
  - docker
before_install:
  - docker build -t hungt/docker-fe -f Dockerfile.dev .
script:
  - docker run hungt/docker-fe npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-fe"
  env: "DockerFe-env"
  bucket_name: "elasticbeanstalk-us-east-1-014150799834"
  bucket_path: "docker-fe"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
